default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: mpa-forms_development

test:
  <<: *default
  database: mpa-forms_test

production:
  <<: *default
  database: mpa-forms_production
  username: mpa-forms
  password: <%= ENV['MPA-FORMS_DATABASE_PASSWORD'] %>
